name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 1' # Weekly scan on Mondays

jobs:
  security:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run npm audit
      run: npm audit --audit-level moderate
    
    - name: Check for known vulnerabilities
      run: npm audit fix --dry-run
      
    - name: Security dependency check
      run: |
        echo "Checking for security vulnerabilities..."
        npm list --depth=0 | grep -E "(dompurify|@types/dompurify)" || echo "DOMPurify not found"
        
    - name: Lint for security issues
      run: |
        echo "Running security linting..."
        # Check for potential XSS vulnerabilities
        grep -r "innerHTML\|outerHTML\|dangerouslySetInnerHTML" --include="*.tsx" --include="*.ts" client/src/ || true
        # Check for eval usage
        grep -r "eval\|Function\|setTimeout.*string\|setInterval.*string" --include="*.tsx" --include="*.ts" client/src/ || true
